# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: book_service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'book_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x62ook_service.proto\x12\tapp.pdytr\"1\n\x04\x42ook\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\"/\n\x0e\x41\x64\x64\x42ookRequest\x12\x1d\n\x04\x62ook\x18\x01 \x01(\x0b\x32\x0f.app.pdytr.Book\"0\n\x0f\x41\x64\x64\x42ookResponse\x12\x1d\n\x04\x62ook\x18\x01 \x01(\x0b\x32\x0f.app.pdytr.Book\"\x12\n\x10ListBooksRequest\"3\n\x11ListBooksResponse\x12\x1e\n\x05\x62ooks\x18\x01 \x03(\x0b\x32\x0f.app.pdytr.Book2\x97\x01\n\x0b\x42ookService\x12@\n\x07\x41\x64\x64\x42ook\x12\x19.app.pdytr.AddBookRequest\x1a\x1a.app.pdytr.AddBookResponse\x12\x46\n\tListBooks\x12\x1b.app.pdytr.ListBooksRequest\x1a\x1c.app.pdytr.ListBooksResponseB\x1d\n\tapp.pdytrB\x10\x42ookServiceProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'book_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\tapp.pdytrB\020BookServiceProto'
  _globals['_BOOK']._serialized_start=33
  _globals['_BOOK']._serialized_end=82
  _globals['_ADDBOOKREQUEST']._serialized_start=84
  _globals['_ADDBOOKREQUEST']._serialized_end=131
  _globals['_ADDBOOKRESPONSE']._serialized_start=133
  _globals['_ADDBOOKRESPONSE']._serialized_end=181
  _globals['_LISTBOOKSREQUEST']._serialized_start=183
  _globals['_LISTBOOKSREQUEST']._serialized_end=201
  _globals['_LISTBOOKSRESPONSE']._serialized_start=203
  _globals['_LISTBOOKSRESPONSE']._serialized_end=254
  _globals['_BOOKSERVICE']._serialized_start=257
  _globals['_BOOKSERVICE']._serialized_end=408
# @@protoc_insertion_point(module_scope)
