# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: experimento.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'experimento.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x65xperimento.proto\x12\x04grpc\"\x19\n\tMyRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\x1d\n\nMyResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2@\n\tMyService\x12\x33\n\x0eSimpleResponse\x12\x0f.grpc.MyRequest\x1a\x10.grpc.MyResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'experimento_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MYREQUEST']._serialized_start=27
  _globals['_MYREQUEST']._serialized_end=52
  _globals['_MYRESPONSE']._serialized_start=54
  _globals['_MYRESPONSE']._serialized_end=83
  _globals['_MYSERVICE']._serialized_start=85
  _globals['_MYSERVICE']._serialized_end=149
# @@protoc_insertion_point(module_scope)
